name: Test for Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        c_compiler: [gcc, clang]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: >
        sudo apt-get update &&
        sudo apt-get install -y libgtk-4-dev

    - name: Configure CMake
      env:
        CC: ${{matrix.compiler}}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      env:
        CC: ${{matrix.compiler}}
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
